# Generated by Django 4.1.2 on 2022-11-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="join_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="User Join Date"),
        ),
    ]
